---
- name: Add ec2-user to docker group
  raw: sudo usermod -aG docker ec2-user
  changed_when: true

- name: Create app directory
  shell: mkdir -p {{ app_dir }} && chown ec2-user:ec2-user {{ app_dir }}
  changed_when: true

- name: Copy application code
  copy:
    src: ../app/
    dest: "{{ app_dir }}/"
    owner: ec2-user
    group: ec2-user

- name: Build and Run Container
  shell: |
    cd {{ app_dir }}
    docker build -t {{ docker_image }} .
    docker rm -f {{ container_name }} || true
    docker run -d -p {{ app_port }}:3000 --name {{ container_name }} {{ docker_image }}